### PR TITLE
Make Crawler.loop actually exist

### PR DESCRIPTION
**Pull request by brettcannon**
Otherwise the attribute seems to never be set.

### CODE REVIEW

**Comment by ajdavis** [comment]
Thanks again @brettcannon ! In this case I see the problem you want to solve but disagree with the method a little, since it [diverges from the actual code so much](https://github.com/aosabook/500lines/blob/71e0672/crawler/code/crawling.py#L50-L54). Here's the class in crawling.py:
```
class Crawler:
    def __init__(self, roots,
                 exclude=None, strict=True,
                 max_redirect=10, max_tries=4,
                 max_tasks=10, *, loop=None):
        self.loop = loop or asyncio.get_event_loop()
```
How about in crawler.markdown, we do?:
```
loop = asyncio.get_event_loop()

crawler = crawling.Crawler('http://xkcd.com',
                           max_redirect=10,
                           loop=loop)

loop.run_until_complete(crawler.crawl())
```
So just like you have it, but with `loop` passed as a final keyword arg instead of an initial positional arg. And then, simply:
```
class Crawler:
    def __init__(self, root_url, max_redirect, loop):
        self.loop = loop
        # ... and the rest of that code example ...
 ```
This is a reasonable compromise, it stays closer to the code in crawling.py but still doesn't weigh down the text with irrelevant details.

**Comment by brettcannon** [comment]
@ajdavis Done! PTAL

**Comment by asvetlov** [comment]
BTW I believe original crawler should have signature like
```
class Crawler:
    def __init__(self, roots, *,
                 exclude=None, strict=True,
                 max_redirect=10, max_tries=4,
                 max_tasks=10, loop=None):
                     ...
```

I mean all parameters except `roots` should be keyword-only.

**Comment by ajdavis** [comment]
@asvetlov I see that idiom a lot in new code in the Python 3 standard library. Is it fair to say that it's now deprecated to declare parameters with default values that can be either positional or keyword? That is, this is now Considered Harmful?:
```
def foo(a=1, b=2):
    pass
```
... and in Python 3 such a function should *always* be declared like:
```
def foo(*, a=1, b=2):
   pass
```

**Comment by brettcannon** [comment]
Keyword-only arguments are typically used in cases where providing the argument by name would be ambiguous. For instance, if you see code like `some_func(1, 2, 3, True)` do you know what `True` means? But if the call was `some_func(1, 2, 3, sum=True)` you have a much better idea. So it doesn't directly have anything to do with default arguments as much as whether context is necessary.

Keyword-only arguments are also fantastic for expanding an API that previously existed where you don't want people using the old version of the API to accidentally succeed in calling something when they pass an extra argument in by accident.

**Comment by ajdavis** [comment]
Interesting.

As for this PR, let's merge it, I think this reads well and keeps the user focused on what matters. Thank you. =)

**Comment by MichaelDiBernardo** [comment]
Thanks all.

**Pull request merged**
